[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
clap = { version = "4.5.27", features = ["derive"]}
serde = { version = "1.0.217", features = ["derive"]}
serde_json = "1.0"